---
title: "Tutorial 5 solutions"
author: "Author: Matthew J. Crossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    # code_folding: show
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, collapse=T)
```

```{r, eval=T}
# load the packages we will need
library(data.table)
library(ggplot2)

# clean session
rm(list=ls())

# 1
ans_1a <- TRUE
ans_1b <- FALSE
ans_1c <- TRUE
ans_1d <- FALSE

# 2
mu <- 15
sigma <- 2.74
ans_2a <- pnorm(17, mu, sigma, lower.tail=F)
ans_2b <- pnorm(14, mu, sigma, lower.tail=T)
ans_2c <- pnorm(20, mu, sigma, lower.tail=F)
ans_2d <- pnorm(13, mu, sigma, lower.tail=T)

n <- 30
p <- 0.5
ans_2e <- pbinom(17, n, p, lower.tail=F)
ans_2f <- pbinom(14, n, p, lower.tail=T)
ans_2g <- pbinom(20-1, n, p, lower.tail=F)
ans_2h <- pbinom(13-1, n, p, lower.tail=T)

# i
# Binomial(n, p) is well approximated by a Normal with mean
# np and variance np(1-p) when n is big enough (about 30)

# 3
ans_3a <- "IV"
ans_3b <- "VII"
ans_3c <- "VIII"
ans_3d <- "VI" 
ans_3e <- "I" 
ans_3f <- "III" 
ans_3g <- "II" 
ans_3h <- "V" 

# 4
d1 <- 5
d2 <- 100
n = 1000

mu_x <- (d2/(d2-2))
sig_x <- (2*(d2^2)*(d1+d2-2))/(d1*(d2-2)^2*(d2-4))

ans_4a <- "Skewed"
ans_4b <- "Decreases"
ans_4c <- "Decreases"
ans_4d <- mu_x
ans_4e <- sig_x / n
```