---
title: "Tutorial 10 Solutions"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solutions

```{r}
library(data.table)
library(ggplot2)
library(ez)

rm(list = ls())

# 1 - follows lecture notes almost exactly
d <- fread("
        a        b        c         d
12.525909  8.92010 15.52719  9.176978
 9.347533 10.14287 12.40198 10.504447
12.659599 11.41056 11.70469  8.216158
12.544859 11.98847 13.42108 10.871367
10.829283 16.80931 13.40157  7.524923           
           ")

a_obs <- d[, a]
b_obs <- d[, b]
c_obs <- d[, c]
d_obs <- d[, d]

na <- length(a_obs)
nb <- length(b_obs)
nc <- length(c_obs)
nd <- length(d_obs)

n_total <- na + nb + nc + nd
n_groups <- 4

## dfs
df_between <- n_groups-1
df_within <- n_total - n_groups

## mean of each group
mean_a <- mean(a_obs)
mean_b <- mean(b_obs)
mean_c <- mean(c_obs)
mean_d <- mean(d_obs)

## grand mean
grand_mean <- mean(c(a_obs, b_obs, c_obs, d_obs))

## ss-between
ss_between <- na*(mean_a - grand_mean)^2 +
  nb*(mean_b - grand_mean)^2 +
  nc*(mean_c - grand_mean)^2 +
  nd*(mean_d - grand_mean)^2

## ss-within --- a better way
ss_within <- sum((a_obs - mean_a)^2) +
  sum((b_obs - mean_b)^2) +
  sum((c_obs - mean_c)^2) +
  sum((d_obs - mean_d)^2)

## mean squares
ms_between <- ss_between / df_between
ms_within <- ss_within / df_within

## observed F-value
f_obs <- ms_between / ms_within

## compute pval
pval <- pf(f_obs, df_between, df_within, lower.tail=F)

## compute critical value
crit_val <- qf(0.05, df_between, df_within, lower.tail=F)

ans_1_obs <- f_obs
ans_1_pval <- pval
ans_1_crit <- crit_val


# 2
# F_obs is equal to 1 when ms_between is equal to ms_within,
# and can only be less than one when ms_within is larger
# than ms_between. This comes directly from the definition
# of F_obs.

ans_2a <- "within"
df_between <- 10
d_within <- 100
ans_2b <- pf(0.5513168, df_between, d_within, lower.tail=F)
ans_2c <- qf(0.05, df_between, d_within, lower.tail=F)


# 3
d <- fread("https://crossley.github.io/cogs2020/data/mis/mis_data.csv")

dd <- d[, .(mean_error = mean(error)), .(condition, subject)]
dd[, condition := factor(condition)]
dd[, subject := factor(subject)]

ez_res <- ezANOVA(
  data=dd,
  dv=mean_error,
  wid=subject,
  between=.(condition),
  type=3
)

ans_3_obs <- ez_res$ANOVA$F
ans_3_pval <- ez_res$ANOVA$p
ans_3_crit <- qf(0.05, ez_res$ANOVA$DFn, ez_res$ANOVA$DFd, lower.tail=F)

# 4
x <- dd[condition==0, mean_error]
y <- dd[condition==1, mean_error]
t_res <- t.test(x,
                y,
                mu=0,
                alternative='two.sided',
                paired=FALSE,
                var.equal=TRUE,
                conf.level=0.95)

ans_4_obs <- t_res$statistic
ans_4_pval <- t_res$p.value
ans_4_crit_lower <- qt(0.05/2, t_res$parameter, lower.tail=T)
ans_4_crit_upper <- qt(0.05/2, t_res$parameter, lower.tail=F)
```