```{r echo=F, message=F, warning=F}
rm(list=ls())
```

# Expected value

## Learning objectives

TODO: fix learning objectives / tidy up content

* Understand how, in principle, to **compute expected
  values** from continuous and discrete random variables.


## Central tendency

We have previously seen that central tendency is given by
the expected value of a random variable, and that for a
discrete a random variable, expected value is given by the
following equation:

\begin{align}
\mathbb{E}\big[X\big] &= \mu \\
     &= x_1 p(x_1) + x_2 p(x_2) + \ldots + x_n p(x_n) \\
     &= \sum_{i}^{n} x_i p(x_i)
\end{align}

When dealing with continuous random variables, this equation
becomes the following:

\begin{align}
\mathbb{E}\big[X\big] &= \mu \\
     &= \int_{a}^{b} f(x) dx
\end{align}

where the possible outcomes of the random variable $X$ are
continuous in the interval $[a, b]$, and $f(x)$ is the pdf
of $X$.

For a normal distribution, this becomes

\begin{align}
\mathbb{E}\big[X\big] &= \mu \\
     &= \int_{-\infty}^{\infty} f(x) dx
\end{align}

because the possible outcomes of a random variable with a
normal distribution are continuous in the interval
$[-\infty, \infty]$.

## Population spread

We saw that for discrete random variables, population
variance is defined as the expected squared deviation from
the mean, as given by the following equation:

\begin{align}
\mathbb{Var}\big[X\big] &= \sigma^2 \\
       &= E((X - \mu)^2) \\
       &= \sum_i x_{i}^2 p(X=x_{i}) - \mu^2
\end{align}

For continuous random variables, this equation becomes the
following:

\begin{align}
\mathbb{Var}\big[X\big] &= \sigma^2 \\
       &= E((X - \mu)^2) \\
       &= \int_{a}^{b} (x - \mu)^2 f(x) dx
\end{align}

For a normal distribution, this becomes:

\begin{align}
\mathbb{Var}\big[X\big] &= \sigma^2 \\
       &= E((X - \mu)^2) \\
       &= \int_{-\infty}^{\infty} (x - \mu)^2 f(x) dx
\end{align}

because the possible outcomes of a random variable with a
normal distribution are continuous in the interval
$[-\infty, \infty]$.


<div style="color:#990000">
**Computing expect values (e.g., population means and
population variances) from continuous random variables
required the evauluation of integrals. I won't expect that
you do that in this course. Rather, it is important that you
understand how to estimate these things from plots.**
<br></br>
</div>


