# What is statistics?
This chapter introduces many of the core concepts underlying
statistical thinking. It covers the idea of descriptive
versus inferential statistics, the relationship between
samples and populations, the concept of a random variable,
the difference between descriptive and inferential
statistics. It lays the groundwork for understanding the
broader role of statistics in experiment design and data
interpretation.

## Casual definition
- Very roughly speaking, we can think of statistics as a
  mathematical tool for describing data using **descriptive
  statistics** and for making decisions on the basis of data
  using **inferential statistics**.

- Visualising the data and computing summary statistics like
  means and standard deviations are standard approaches for
  descriptive statistics.

- Using Null Hypothesis Significance Testing (NHST) is the
  conventional approach for inferential statistics.

## Why are statistics necessary?
- Statistical methods are useful whenever the outcomes of an
  experiment you would like to summarise and interpret are
  at least a little bit random.

- For example, imagine trying to determine if a coin is fair
  coin (i.e., equal probability of landing heads as landing
  tails) or not. Can you make a good decision after just one
  flip? Certainly not. This is because you know that the
  outcome of each flip is random, so seeing one measly flip
  tells you next to nothing. Rather, you need to flip it a
  bunch of times, and then think very carefully about the
  pattern of outcomes that you observed. The *thinking very
  carefully* part is where statistics comes in to save the
  day.

## More formal definition
- In statistics, we have special terminology to refer to the
  process that generates random outcomes of an experiment
  --- we call it a **random variable**. Any particular
  single outcome or sometimes a set of random outcomes from
  an experiment is called a **sample** from the random
  variable.

- **random variable**: Data generating process.

- **sample**: A set of measurements obtained from a random
  variable.

- **descriptive statistics**: Summary of a sample.

- **inferential statistics**: A method to make inferences /
  educated guesses about the *true* state of the random
  variable that generated a sample.

- For example, Suppose I am interested in knowing about
  spontaneous number generation in the human mind.  I
  perform an experiment in which I ask everybody in the room
  to shout out any number they wish. The result of this
  request is a lot of numbers and looking at them all at
  once is a bit overwhelming.  To help me think about
  things, I compute the average.  After carefully thinking
  about things, I make a decision about what numbers I think
  are most likely to come from this experiment in the
  future. In particular, I know that the numbers I will get
  are almost certainly going to be different numbers, but I
  also suspect that they are likely to be close to the
  average I just computed.

--
TODO: ask chatgpt to generate numbers and add to the file
--

- The **random variable** in this example is the process
  that generated the data. That is, me asking people to
  shout out any number.

- The **sample** is the set of numbers I actually obtained.

- The average of those numbers is a **descriptive
  statistic**.

- The **method** that I use to make a decision about numbers
  that I think I am likely to get in the future, should I
  ever do this experiment again is the main topic of
  **inferential statistics**.

### More general example
In statistics, it is safe to think of all data as coming
from an experiment (i.e., a random variable). These numbers
are called a **sample**. In general, if we perform an
experiment in which we observe $n$ outcomes, then our sample
is written as:

$$
\boldsymbol{x} = ( x_1, x_2, x_3, ..., x_n )
$$

For example, we might perform an experiment where we observe
a rat navigate a maze several times, and measure the time to
completion for each maze run. Suppose that we observed 10
runs with the following times in seconds:

$$
\boldsymbol{x} = ( 52.38, 55.41, 70.88, 43.30, 50.15, 41.99, 36.82, 34.05, 52.70, 72.25 )
$$

We would say that $\boldsymbol{x}$ is our sample. 

If somebody asks you about your experiment, it is often not
very practical to list all the numbers that you observed.
Instead, you would want some way to concisely summarise the
sample that you obtained. In a later chapter, we will cover
some basic **descriptive statistics** that do exactly this.

In general, we may not want to merely describe our data, but
we may want to use it to help us make decisions. For
example, suppose that any rat that can reliably run this
maze in under 50 seconds is considered a super-mega-genius.
Should you put in the super-mega-genius paperwork for this
rat? Later in the course, we will go deeper into the
**inferential statistics** that will help us in this
scenario, but we will begin developing an intuition now.

As it turns out, answering this question intelligently
requires using our **sample** to make inferences about a
**population**, which in this case can be roughly thought of
as the set of all possible maze times and their relative
frequencies that you will ever observe if you run this
experiment forever.

* **population**: The set of all possible outcomes of an
  experiment.
* **sample**: A particular outcome obtained when the
  experiment is performed.

For example, if you perform your experiment another two
times, you might end up with the following samples:

$$
\boldsymbol{x_1} = ( 52.38, 55.41, 70.88, 43.30, 50.15, 41.99, 36.82, 34.05, 52.70, 72.25 )
$$
$$
\boldsymbol{x_2} = ( 62.36, 53.89, 53.95, 33.81, 61.12, 61.48, 36.89, 49.45, 52.50, 50.95 )
$$
$$
\boldsymbol{x_3} = ( 52.04, 48.28, 48.12, 58.89, 51.76, 42.88, 49.04, 60.41, 53.99, 70.06 )
$$

Each sample is composed of very similar but not identical
observations. A **random variable** is a process that
generates outcomes for a particular experiment, a
**population** is the collection of all possible outcomes,
and a **sample** is a particular outcome obtained when the
experiment is performed (i.e., $\boldsymbol{x_1}$,
$\boldsymbol{x_2}$ and $\boldsymbol{x_3}$ above). In
statistics, we want to estimate properties of the
**population** by using our **sample**.

## Summary of key concepts
- **random variable**: A process that generates random
  outcomes.

- **population**: The set of all possible outcomes of an
  experiment.

- **sample**: A set of measurements obtained from a random
  variable.

- **descriptive statistics**: Summary of a sample.

- **inferential statistics**: A method to make inferences /
  educated guesses about the *true* state of the random
  variable that generated a sample.
